name: Deploy React to GitHub Pages
on:
  push:
    branches: [master]        # or whichever branch you work on
permissions:
  contents: read
  pages: write
  id-token: write           # needed for Deployment Environment
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci           # reproducible install
      - run: npm run build    # produces build/ directory
      - uses: actions/upload-pages-artifact@v3   # ⬆ upload build/
        with:
          path: ./build
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4            # ⬇ publish

